### ISSUE TITLE
CLI Options

### ISSUE THREAD

**Issue by peteringram0** [jescalan/autoprefixer-stylus#127]
Hey, 

Im using the autoprefixer via CLI like so 

````
./node_modules/stylus/bin/stylus -u ./node_modules/autoprefixer-stylus ./src/styles.styl
````

How do i pass in the options this way please?

e.g.
````
{ browsers: ['> 0%'] }
````

**Comment by jescalan** [comment]
https://github.com/jescalan/autoprefixer-stylus/issues/86
