### ISSUE TITLE
transition-property: transform adds a prefix -webkit-transform

### ISSUE THREAD

**Issue by alexwendte** [jescalan/autoprefixer-stylus#177]
Example of what I am talking about.

Here is my stylus:
```
span.expand
  color: #7e7f81  
  font-size: 2rem  
  font-weight: bold
  transition-property: transform
```

Here is the css that compiles

```
span.expand
  color: #7e7f81;
  font-size: 2rem;
  font-weight: bold;
  -webkit-transition-property: -webkit-transform;
  transition-property: -webkit-transform;
  transition-property: transform;
  transition-property: transform, -webkit-transform;
```

I believe it is redundant to have so many prefixes.

**Comment by brwnrclse** [comment]
Hello, I just tested out your posted css in the Autoprefixer online site and it seems like that's the right amount of prefixes. Here's a screengrab for reference
<img width="1400" alt="Screen Shot 2019-07-12 at 10 05 07 AM" src="https://user-images.githubusercontent.com/22730252/61134172-0273d380-a48d-11e9-9bbd-c6b52fcd02ab.png">


Also the browserlist query i entered is:
`last 4 version, not dead, not ie <= 11`

**Comment by jescalan** [comment]
If you have questions about the prefixes added, please open up an issue in [autoprefixer](https://github.com/postcss/autoprefixer) - this is simply an adapter for stylus.
