### ISSUE TITLE
Publish after each update or use ^ or ~ in package.json

### ISSUE THREAD

**Issue by JSteunou** [jescalan/autoprefixer-stylus#60]
Your bot auto update your dependencies which is nice, but this lib is not published after each update which is less nice.

Could you consider publish a new version so we can get the last autoprefixer and then looking at maybe setting autoprefixer to `6.x.x` or `6.3.x` in package.json please.

**Comment by jenius** [comment]
Published! I'll be more on point with future releases, not getting rid of greenkeeper though :grin:

**Comment by JSteunou** [comment]
Eheh i understand. Thank you
Le 22 janv. 2016 18:11, "Jeff Escalante" <notifications@github.com> a
écrit :
